steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/evolution-api:${_TAG}',
      '.'
    ]

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/evolution-api:${_TAG}'
    ]

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/${_ENV}/
    - --location=${_REGION}
    - --cluster=evolution-cluster

  # Update deployment with new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 
      'image', 
      'deployment/evolution-api',
      'evolution-api=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/evolution-api:${_TAG}'
    ]
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=evolution-cluster'

timeout: '1800s'

substitutions:
  _ENV: 'staging'  # default value, will be overridden by trigger
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY: 'evolution-registry'
  _TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 