apiVersion: v1
kind: Secret
metadata:
  name: evolution-secrets
  namespace: evolution-staging
type: Opaque
data:
  AUTHENTICATION_API_KEY: <base64-encoded-key>
  DATABASE_CONNECTION_URI: <base64-encoded-uri>
  # Add other sensitive configurations 